name: Build and Package
on:
  pull_request:
    branches: ["main"]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            gcc \
            g++ \
            libwayland-dev \
            wayland-protocols \
            libgl1-mesa-dev \
            libegl1-mesa-dev \
            libfontconfig1-dev \
            libxkbcommon-dev \
            libsdbus-c++-dev \
            libpipewire-0.3-dev \
            pkg-config

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Package
        run: |
          cd build
          cpack

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-packages
          path: |
            build/*.deb
            build/*.tar.gz

  build-arch:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm \
            base-devel \
            cmake \
            gcc \
            git \
            wayland \
            wayland-protocols \
            mesa \
            fontconfig \
            libxkbcommon \
            sdbus-cpp \
            pipewire \
            pkgconf

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Package
        run: |
          cd build
          cpack

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: arch-packages
          path: build/*.tar.gz

  build-centos:
    runs-on: ubuntu-latest
    container: quay.io/centos/centos:stream9
    steps:
      - name: Install dependencies
        run: |
          dnf install -y epel-release
          dnf config-manager --set-enabled crb
          dnf install -y \
            cmake \
            gcc \
            gcc-c++ \
            git \
            wayland-devel \
            wayland-protocols-devel \
            mesa-libGL-devel \
            mesa-libEGL-devel \
            fontconfig-devel \
            libxkbcommon-devel \
            pipewire-devel \
            pkgconfig \
            rpm-build

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install sdbus-cpp (not in CentOS repos)
        run: |
          dnf install -y systemd-devel expat-devel
          git clone https://github.com/Kistler-Group/sdbus-cpp.git
          cd sdbus-cpp
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
          make -j$(nproc)
          make install

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Package
        run: |
          cd build
          cpack

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: centos-packages
          path: |
            build/*.rpm
            build/*.tar.gz
